# Generated by Django 4.1.5 on 2023-01-16 07:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaryApp', '0002_entry_main_delete_main_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='date_sort',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 16, 18, 41, 12, 749558)),
        ),
    ]
