# Generated by Django 4.1.5 on 2023-01-16 07:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaryApp', '0003_entry_date_sort'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-date_sort']},
        ),
        migrations.AlterField(
            model_name='entry',
            name='date_sort',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
