# Generated by Django 4.1.5 on 2023-01-16 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaryApp', '0004_alter_entry_options_alter_entry_date_sort'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={},
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='date',
            new_name='entry_date',
        ),
        migrations.AlterField(
            model_name='entry',
            name='date_sort',
            field=models.DateField(),
        ),
    ]
